### PR TITLE
Merging basic copy changes

### PR DESCRIPTION
**Pull request by noahmanger**
This includes a handful of copy changes that Treasury requested and approved, as well as some slight page-nav restyling to accommodate only three items, as the employer page now has (instead of 4).

I also reverted the latest analytics additions on master and will push those up with these edits.

### CODE REVIEW

**Comment by noahmanger** [comment]
@konklone I foolishly told them I would push these changes up tonight but didn't take into account that I should have had somebody else merge this PR for me. If you happen to be on and get a chance, go for it. Otherwise I think I'll just do it myself unless anyone strongly objects.

**Comment by konklone** [comment]
:+1:

**Comment by noahmanger** [comment]
Thanks!

On Thu, Mar 5, 2015 at 5:14 PM, Eric Mill <notifications@github.com> wrote:

> Merged #163 <https://github.com/18F/myra/pull/163>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/myra/pull/163#event-247231222>.
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146

**Comment by konklone** [comment]
There was a spike in traffic on March 4th, the day before deploying this. So, it's difficult to know whether the traffic since then (which is raised over what we observed prior to deploying this) can be attributed to the spike, or to the reverted analytics snippet.

**Comment by noahmanger** [comment]
Yeah, I agree. Let's see how it goes the next few days. I agree with you
that the drop wasn't that significant.

On Mon, Mar 9, 2015 at 8:33 AM, Eric Mill <notifications@github.com> wrote:

> There was a spike in traffic on March 4th, the day before deploying this.
> So, it's difficult to know whether the traffic since then (which is raised
> over what we observed prior to deploying this) can be attributed to the
> spike, or to the reverted analytics snippet.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/myra/pull/163#issuecomment-77876502>.
>



-- 
Noah Manger
18F <http://18f.gsa.gov> | Work: 415-696-6146

**Pull request merged**
